version: '3.7'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - './:/var/www'
      - './docker/nginx/conf.d/:/etc/nginx/conf.d/'
    environment:
      VIRTUAL_HOST: 'challenge.localhost'

  database:
    container_name: database
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - './docker/mysql/:/etc/mysql/conf.d/'
      - 'mysql:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: root

  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    working_dir: /var/www
    volumes:
      - './:/var/www'

volumes:
  mysql:
    name: mysql
